### ISSUE TITLE
[Feat] Browse local files

### ISSUE THREAD

**Issue by heartbleeded** [Nyx0uf/shinobu#1]
Great work!

I would be nice if there's a way to browse local files. Now I have many songs with no metadata, so I need to walk through subdirectories and look for wanted file names is the only way unfortunately for me.

Here's the same feature in [Cantata](https://github.com/CDrummond/cantata)

<img width="256" alt="cantata" src="https://user-images.githubusercontent.com/7350821/68156164-8fb2ca80-ff4b-11e9-8358-a1e36208c832.png">

Merci.

**Comment by Nyx0uf** [comment]
Probably won't do. It requires quite some work and I have no usage for this, as my library is well tagged.

I'm letting the issue open in case someone wants to implement it.

**Comment by Nyx0uf** [comment]
@heartbleeded

implemented in https://github.com/Nyx0uf/shinobu/commit/91ec13341cd181b40c7aef919428be835a02fb4c
A toggle setting has been added in the settings section, it is disabled by default.
