### ISSUE TITLE
is it possible to build on a macos VM, and install the built app on an iphone?

### ISSUE THREAD

**Issue by nikita-skobov** [Nyx0uf/shinobu#3]
I know the README says "either you have access to a Mac, or you run macOS on a Virtual Machine", but I just want to check if you (@Nyx0uf ) or anyone else has done it that way before.

If its possible, I would like to try that out, and if successful I'd like to contribute documentation step by step guide to the README on how to build this and put it on an iphone.

This looks like a great project, and I hope I can build this without having to buy a mac

**Comment by Nyx0uf** [comment]
Never tried, but it should work without any problem
