### ISSUE TITLE
kUTTypeJPEG deprecated

### ISSUE THREAD

**Issue by guestguestguestguest** [Nyx0uf/shinobu#5]
In UIImage extension, func save(url: URL) the call to CGImageDestinationCreateWithURL() argument type kUTTypeJPEG has been deprecated.  It builds without error by changing that arg to UTType.jpeg.identifier as CFString.

**Comment by Nyx0uf** [comment]
I don't understand, already done on october 2022 : [Shinobu/src/common/extensions/UIImage+Extensions.swift](https://github.com/Nyx0uf/Shinobu/commit/8bbe77d48ac67a3602d087de3c3a30441fb8e8ff#diff-226006becf3d38194e9fb53a020ed6b63435d17d0576d8c1636b756650e22c01)

**Comment by guestguestguestguest** [comment]
Sorry you're right, I was building from an old source.

F
